### ISSUE TITLE
Update the title to make it clear that we support both RHEL6 and RHEL7

### ISSUE THREAD

**Issue by aaronlippold** [USGS-CIDA/stig#106]

**Comment by isuftin** [comment]
@aaronlippold Should probably do a full test with RHEL6/7. Looks like based on your recently submitted issue, RHEL6/7 may still be buggy.

**Comment by aaronlippold** [comment]
Correct. @samcornwell and @cpoma are working together to do a full set of testing. We do - amazingly - have requests to create an inspec profile for RHEL6 as well as folks are - incredibility - still using RHEL6... !!??

**Comment by isuftin** [comment]
Sadly... yes :)
