### ISSUE TITLE
sysctl ignore_error not working as expected

### ISSUE THREAD

**Issue by isuftin** [USGS-CIDA/stig#115]
https://github.com/sous-chefs/sysctl/issues/110

It seems as though the "ignore_error" flag is being ignored.

**Comment by cpoma** [comment]
The "quick" fix in proc_hard is to allow 255 to be a valid return code. You get 255 for keys that don't exist on the system:
```ruby
node['sysctl']['params'].each do |param, value|
  sysctl_param param do
    key param
    value value
    only_if "sysctl -n -e #{param}"
    return [0,255]
  end
end
```

**Comment by isuftin** [comment]
@cpoma I think the guard that was added in the PR https://github.com/USGS-CIDA/stig/pull/116 (and shown in your example) perform the same task. So in the example above, I don't think the sysctl_param resource would ever be called if the key didn't exist because only_if would block that. Therefore the return would never be considered. Also, if you do remove the guard and only leave the return, you will not see an idempotent run since it will always try to perform the sysctl_param call and always return 255, thinking that yes, it ran.

With the guard in place, I think that works around this issue.
